/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manipulationdefichiers;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * 
 * EditeFichierPanel est la classe représentant un JPanel d'édition de fichier.
 * Elle hérite de JPanel.
 * 
 * @author Pierre-Nicolas
 */
public class EditeFichierPanel extends javax.swing.JPanel {

    /**
     * Retourner le jtextarea du contenu du fichier.
     * @return Le jtextarea du contenu du fichier.
     */
    public JTextArea getjTextAreaContenuFichier() {
        return this.jTextAreaContenuFichier;
    }

    /**
     * Retourner le jtextfield du nom du fichier.
     * @return Le jtextfield du nom du fichier.
     */
    public JTextField getjTextFieldNomFichier() {
        return this.jTextFieldNomFichier;
    }

    /**
     * Retourner le jtextfield de l'extension du fichier.
     * @return Le jtextfield de l'extension du fichier.
     */
    public JTextField getjTextFieldExtensionFichier() {
        return this.jTextFieldExtensionFichier;
    }

    /**
     * Retourner le jbutton de validation d'édition du contenu du fichier.
     * @return Le jbutton de validation d'édition du contenu du fichier.
     */
    public JButton getjButtonEditeContenuFichier() {
        return this.jButtonEditeContenuFichier;
    }

    /**
     * Retourner le jbutton de validation d'édition du nom du fichier.
     * @return Le jbutton de validation d'édition du nom du fichier.
     */
    public JButton getjButtonEditeNomFichier() {
        return this.jButtonEditeNomFichier;
    }
    
    /**
     * Constructeur EditeFichierPanel sans paramètres.
     */
    public EditeFichierPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaContenuFichier = new javax.swing.JTextArea();
        jTextFieldNomFichier = new javax.swing.JTextField();
        jButtonEditeContenuFichier = new javax.swing.JButton();
        jButtonEditeNomFichier = new javax.swing.JButton();
        jTextFieldExtensionFichier = new javax.swing.JTextField();
        jLabelContenuFichier = new javax.swing.JLabel();
        jLabelExtensionFichier = new javax.swing.JLabel();
        jLabelNomFichier = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(830, 550));
        setPreferredSize(new java.awt.Dimension(830, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaContenuFichier.setColumns(20);
        jTextAreaContenuFichier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextAreaContenuFichier.setRows(5);
        jScrollPane1.setViewportView(jTextAreaContenuFichier);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 760, 380));

        jTextFieldNomFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jTextFieldNomFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 269, 30));

        jButtonEditeContenuFichier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditeContenuFichier.setText("Sauvegarder");
        add(jButtonEditeContenuFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 146, 33));

        jButtonEditeNomFichier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEditeNomFichier.setText("Sauvegarder");
        add(jButtonEditeNomFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 146, 33));

        jTextFieldExtensionFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jTextFieldExtensionFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 105, 30));

        jLabelContenuFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelContenuFichier.setText("Contenu :");
        add(jLabelContenuFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 85, -1, -1));

        jLabelExtensionFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelExtensionFichier.setText("Extension :");
        add(jLabelExtensionFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 25, -1, -1));

        jLabelNomFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelNomFichier.setText("Nom :");
        add(jLabelNomFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditeContenuFichier;
    private javax.swing.JButton jButtonEditeNomFichier;
    private javax.swing.JLabel jLabelContenuFichier;
    private javax.swing.JLabel jLabelExtensionFichier;
    private javax.swing.JLabel jLabelNomFichier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaContenuFichier;
    private javax.swing.JTextField jTextFieldExtensionFichier;
    private javax.swing.JTextField jTextFieldNomFichier;
    // End of variables declaration//GEN-END:variables

}
