/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manipulationdefichiers;

import javax.swing.JList;
import manipulationdefichiers_gestionfichierihm.FichierIhm;

/**
 * 
 * ListeFichiersPanel est la classe représentant un JPanel présentant la liste des fichiers du dossier sélectionné dans le JTree.
 * Elle hérite de JPanel.
 * 
 * @author Pierre-Nicolas
 */
public class ListeFichiersPanel extends javax.swing.JPanel {

    /**
     * Retourner la jlist de FichierIhm qui contient la liste des FichierIhm du dossier sélectionné dans le JTree.
     * @return La jlist de FichierIhm qui contient la liste des FichierIhm du dossier sélectionné dans le JTree.
     */
    public JList<FichierIhm> getjListListeFichiersDossierSelectionne() {
        return jListListeFichiersDossierSelectionne;
    }

    /**
     * Constructeur ListeFichiersPanel sans paramètres.
     */
    public ListeFichiersPanel() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListListeFichiersDossierSelectionne = new javax.swing.JList<FichierIhm>();

        setMinimumSize(new java.awt.Dimension(830, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListListeFichiersDossierSelectionne.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jListListeFichiersDossierSelectionne.setModel(new javax.swing.DefaultListModel<FichierIhm>());
        jScrollPane1.setViewportView(jListListeFichiersDossierSelectionne);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 27, 766, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<FichierIhm> jListListeFichiersDossierSelectionne;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
