/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manipulationdefichiers;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import manipulationdefichiers_gestionfichierihm.FichierIhmListeOccurencesMot;

/**
 * 
 * ListerOccurencesMotPanel est la classe représentant un JPanel présentant la liste des occurrences d'un mot dans la liste des fichiers du dossier sélectionné dans le JTree.
 * Elle hérite de JPanel.
 * 
 * @author Pierre-Nicolas
 */
public class ListerOccurencesMotPanel extends javax.swing.JPanel {

    /**
     * Retourner le jlabel du nom du dossier contenant la liste de fichiers du dossier sélectionné dans le JTree.
     * @return Le jlabel du nom du dossier contenant la liste de fichiers du dossier sélectionné dans le JTree.
     */
    public JLabel getjLabelListerFichier() {
        return this.jLabelListerFichier;
    }
    
    /**
     * Retourner la jlist de FichierIhm qui contient la liste des FichierIhm du dossier sélectionné dans le JTree.
     * @return La jlist de FichierIhm qui contient la liste des FichierIhm du dossier sélectionné dans le JTree.
     */
    public JList<FichierIhmListeOccurencesMot> getjListListeFichiersALister() {
        return this.jListListeFichiersALister;
    }

    /**
     * Retourner le jtextfield du mot de recherche dans les fichiers du dossier sélectionné dans le JTree.
     * @return Le jtextfield du mot de recherche dans les fichiers du dossier sélectionné dans le JTree.
     */
    public JTextField getjTextFieldListerFichier() {
        return this.jTextFieldListerFichier;
    }

    /**
     * Retourner le jbutton listant les occurrences d'un mot dans la liste des fichiers du dossier sélectionné dans le JTree.
     * @return Le jbutton listant les occurrences d'un mot dans la liste des fichiers du dossier sélectionné dans le JTree.
     */
    public JButton getjButtonLister() {
        return this.jButtonLister;
    }

    /**
     * Constructeur ListerOccurencesMotPanel sans paramètres.
     */
    public ListerOccurencesMotPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelListerFichier = new javax.swing.JLabel();
        jTextFieldListerFichier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListeFichiersALister = new javax.swing.JList<FichierIhmListeOccurencesMot>();
        jButtonLister = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(830, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(830, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelListerFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelListerFichier.setText("Lister tous les fichiers qui contiennent le mot :");
        add(jLabelListerFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 320, 30));

        jTextFieldListerFichier.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jTextFieldListerFichier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 279, 30));

        jListListeFichiersALister.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jListListeFichiersALister.setModel(new javax.swing.DefaultListModel<FichierIhmListeOccurencesMot>());
        jScrollPane1.setViewportView(jListListeFichiersALister);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 750, 400));

        jButtonLister.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonLister.setText("Lister");
        add(jButtonLister, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 99, 34));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLister;
    private javax.swing.JLabel jLabelListerFichier;
    private javax.swing.JList<FichierIhmListeOccurencesMot> jListListeFichiersALister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldListerFichier;
    // End of variables declaration//GEN-END:variables
}
