/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manipulationdefichiers;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextField;
import manipulationdefichiers_gestionfichierihm.FichierIhm;

/**
 * 
 * ListeFichiersAConcatenerPanel est la classe représentant un JPanel présentant la liste des fichiers à concaténer.
 * Elle hérite de JPanel.
 * 
 * @author Pierre-Nicolas
 */
public class ListeFichiersAConcatenerPanel extends javax.swing.JPanel {

    /**
     * Retourner le jbutton qui descend un fichier dans l'ordre de concaténation.
     * @return Le jbutton qui descend un fichier dans l'ordre de concaténation.
     */
    public JButton getjButtonBas() {
        return this.jButtonBas;
    }

    /**
     * Retourner le jbutton qui concatène la liste des fichiers.
     * @return Le jbutton qui concatène la liste des fichiers.
     */
    public JButton getjButtonConcatener() {
        return this.jButtonConcatener;
    }
    
    /**
     * Retourner le jbutton qui monte un fichier dans l'ordre de concaténation.
     * @return Le jbutton qui monte un fichier dans l'ordre de concaténation.
     */
    public JButton getjButtonHaut() {
        return this.jButtonHaut;
    }
    
    /**
     * Retourner le jbutton qui ajoute un fichier à concaténer ne provenant pas du dossier sélectionné.
     * @return Le jbutton qui ajoute un fichier à concaténer ne provenant pas du dossier sélectionné.
     */
    public JButton getjButtonAjouterFichierExterieur() {
        return this.jButtonAjouterFichierExterieur;
    }
    
    /**
     * Retourner la jlist de FichierIhm qui contient la liste des FichierIhm à concaténer.
     * @return La jlist de FichierIhm qui contient la liste des FichierIhm à concaténer.
     */
    public JList<FichierIhm> getjListListeFichiersDossierSelectionne() {
        return this.jListListeFichiersDossierSelectionne;
    }
    
    /**
     * Retourner le jtextfield du nom du fichier concaténé.
     * @return Le jtextfield du nom du fichier concaténé.
     */
    public JTextField getjTextFieldNomFichierConcatene() {
        return this.jTextFieldNomFichierConcatene;
    }

    /**
     * Constructeur ListeFichiersAConcatenerPanel sans paramètres.
     */
    public ListeFichiersAConcatenerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListListeFichiersDossierSelectionne = new javax.swing.JList<FichierIhm>();
        jButtonConcatener = new javax.swing.JButton();
        jButtonHaut = new javax.swing.JButton();
        jButtonBas = new javax.swing.JButton();
        jLabelTexteConcatener = new javax.swing.JLabel();
        jButtonAjouterFichierExterieur = new javax.swing.JButton();
        jTextFieldNomFichierConcatene = new javax.swing.JTextField();
        jLabelTexteNomFichierConcatene2 = new javax.swing.JLabel();
        jLabelTexteNomFichierConcatene1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(830, 550));
        setPreferredSize(new java.awt.Dimension(830, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListListeFichiersDossierSelectionne.setFont(new java.awt.Font("Arial", 0, 14));
        jListListeFichiersDossierSelectionne.setModel(new javax.swing.DefaultListModel<FichierIhm>());
        jScrollPane1.setViewportView(jListListeFichiersDossierSelectionne);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 670, 420));

        jButtonConcatener.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonConcatener.setText("Concaténer");
        add(jButtonConcatener, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 146, 33));

        jButtonHaut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonHaut.setText("Haut");
        add(jButtonHaut, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, 33));

        jButtonBas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonBas.setText("Bas");
        add(jButtonBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 61, 33));

        jLabelTexteConcatener.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTexteConcatener.setText("Réordonner les fichiers à concaténer :");
        add(jLabelTexteConcatener, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonAjouterFichierExterieur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonAjouterFichierExterieur.setText("Ajouter des fichiers ne provenant pas du dossier sélectionné");
        add(jButtonAjouterFichierExterieur, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 33));

        jTextFieldNomFichierConcatene.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        add(jTextFieldNomFichierConcatene, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 180, 30));

        jLabelTexteNomFichierConcatene2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTexteNomFichierConcatene2.setText("(par défaut nom du premier fichier)");
        add(jLabelTexteNomFichierConcatene2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 15, 400, 30));

        jLabelTexteNomFichierConcatene1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTexteNomFichierConcatene1.setText("Nom du fichier concaténé :");
        add(jLabelTexteNomFichierConcatene1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 400, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterFichierExterieur;
    private javax.swing.JButton jButtonBas;
    private javax.swing.JButton jButtonConcatener;
    private javax.swing.JButton jButtonHaut;
    private javax.swing.JLabel jLabelTexteConcatener;
    private javax.swing.JLabel jLabelTexteNomFichierConcatene1;
    private javax.swing.JLabel jLabelTexteNomFichierConcatene2;
    private javax.swing.JList<FichierIhm> jListListeFichiersDossierSelectionne;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNomFichierConcatene;
    // End of variables declaration//GEN-END:variables
}
